name: Validate

on:
  push:
    branches: [main, dev, stg]
  pull_request:
    branches: [main, dev, stg]

permissions:
  contents: read

jobs:
  base:
    name: Base validation
    uses: ./.github/workflows/validate.yml
    with:
      is_pull_request: ${{ github.event_name == 'pull_request' }}

  modules-hub:
    name: modules-hub checks
    uses: ./.github/workflows/validate-modules-hub.yml
