name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/self-validate.yml
    with:
      is_pull_request: ${{ github.event_name == 'pull_request' }}
